### ISSUE TITLE
French Translation ?

### ISSUE THREAD

**Issue by daamien** [red-hat-people-team/open-decision-framework#18]
Hi !

My name's Damien Clochard and I'm working for Dalibo, a worker-owned company in France providing PostgreSQL services, training and support ( see http://www.dalibo.com/en/ for more details ). We try to apply open source principles to our own management structure and we're interested in other experiences.

I'd like to translate the Open Decision Framework in French. Do you know a translation project is already started in French or in another language ? If not what's the best way to work and submit my translation ? Is there a defined process for that ?

**Comment by ruhbehka** [comment]
Hi Damien - that's awesome! I'd say just fork the project and translate from whatever file format is easiest for you to work with, then submit a pull request and I'll figure out how and where to add the translated version to the repo.

Thanks,
Rebecca

**Comment by semioticrobotic** [comment]
This is cool, @daamien! Are you familiar with the work of the [open organization ambassadors](https://github.com/open-organization-ambassadors/)? That group is always interested in hearing from companies like Dalibo, who are operating according to open principles and practices. You may find the group's resources helpful in your work. We'd also love to connect with you on [Opensource.com](https://opensource.com/open-organization) and hear your story!

**Comment by daamien** [comment]
Thanks for the quick reply, I'll take a look at the Open Organization Ambassadors repo and check the resources. 

I started the translation effort this morning. Here's an early draft:

https://github.com/dalibo/open-decision-framework/blob/french_translation/ODF-community.french.md

As expected the translation raised a few questions and some wording need clarification. If that's ok for you I'm going to close this issue and open separate issues for each question I have.
