### ISSUE TITLE
[Translation] Modified versions must remove all Red Hat branding.

### ISSUE THREAD

**Issue by daamien** [red-hat-people-team/open-decision-framework#19]
Hi,

In line 7, the trademark statement says : "[Modified versions must remove all Red Hat branding](https://github.com/red-hat-people-team/open-decision-framework/blob/master/ODF-community.md)" 

Assuming that a translation is a modification of the document, I'm unclear how I should translate a sentence like this:

``Impact on Red Hat's culture`` 

Should I keep the name of Red Hat like this:

``Impact sur la culture de Red Hat``

or remove it and translate to a more generic wording for like this:

``Impact sur la culture de la société``

I'm ok with both, just tell me what's the best way to handle this :-)

**Comment by ruhbehka** [comment]
Good question. I'm thinking that since this is a 1:1 translation, let's keep it as "Red Hat." If someone creates a generic version of the framework later on, then we could pretty easily clone this translation and change it to "your organization" instead. Does that work for you?

**Comment by daamien** [comment]
Agreed. 

Thanks for the answer. The translation is almost ready. I'll send a Pull Request in a few days.
