### ISSUE TITLE
[Translation] Definition of "Associates"

### ISSUE THREAD

**Issue by daamien** [red-hat-people-team/open-decision-framework#20]
Hi !

I have a question regarding the terme "associate" which is used many times in the document. For instance:  ``Tell associates where to find detailed information``

Is it a synonym for ``Red Hat employees`` ? Or does apply to a special subset of the company staff ? The French word ``Associés`` means ``Shareholders`` which sounds like a mistranslation to me...

Any input on that is welcome.

**Comment by ruhbehka** [comment]
Yes, it is a synonym for employees. I would just use the French word for "employees" if that is the best way to translate!
