### ISSUE TITLE
English PDF doesn't load

### ISSUE THREAD

**Issue by amber9904** [red-hat-people-team/open-decision-framework#25]
When I try to access or download the PDF (English), I get the following error.

![screen shot 2017-04-14 at 12 53 11 pm](https://cloud.githubusercontent.com/assets/1700043/25049771/69b51286-2111-11e7-8f12-f66cda7d63d9.png)

Reloading the page doesn't help.

**Comment by semioticrobotic** [comment]
GitHub often has difficulty rendering large PDF documents in-line, @amber9904. I recommend:

1. Clicking the filename of the item you wish to download
2. Locating the "Download" button in the upper right-hand corner of the page.
3. Clicking that, even as you receive the same error message as in your screenshot.
4. Waiting for your browser's file download prompt to kick in.

Hopefully that helps.
