### ISSUE TITLE
The Open Source Way handbook < url leads to >  Not Found

### ISSUE THREAD

**Issue by raoulkramer** [red-hat-people-team/open-decision-framework#49]
line 358 `  - [The Open Source Way handbook](https://www.theopensourceway.org/wiki/Introduction) – a guide to creating and nurturing communities of contributors`

Leads to:

Not Found
The requested URL /wiki/Introduction was not found on this server.

-----
Proposed solution:

line 358 `  - [The Open Source Way handbook](https://www.theopensourceway.org) – a guide to creating and nurturing communities of contributors`

**Comment by semioticrobotic** [comment]
Thanks very much for catching this, @raoulkramer! I've just [pushed an update](https://github.com/red-hat-people-team/open-decision-framework/commit/4a77ef4359398c1d6a7229a29c512159319f895f) that fixes this. I'll leave it to the localization teams to do their thing.
